#!/bin/bash

# Küsi kasutajalt reisijate arvu ja kohtade arvu ühes bussis
echo -n "Sisesta reisijate arv: "
read reisijad

echo -n "Sisesta kohtade arv ühes bussis: "
read kohad_bussis

# Arvuta, mitu täis bussi on ja mitu inimest jääb maha
tais_bussid=$((reisijad / kohad_bussis))
ulejaanud=$((reisijad % kohad_bussis))

# Väljasta tulemused
echo "Täidetud busse: $tais_bussid"
echo "Mahajäänud reisijate arv: $ulejaanud"
