#!/bin/bash
#Teiseldus kuupäevale
DATE=$(date +"%D")
#Teiseldus kellajale
TIME=$(date +"%H:%M")
#Teiseldus kalendrile
CALENDAR=$(cal | tail -n 7)
#Skript mis RETURNIB kalendri koos kuupäeva ja kellajaga
echo
echo "Today is $DATE"
echo
echo "Time is $TIME"
echo
echo "$CALENDAR"
