#!/bin/bash
#Teiseldus kuupäevale
DATE=$(date +"%D")
#Teiseldus kellajale
TIME=$(date +"%H:%M")
#Teiseldus kalendrile
CALENDAR=$(ncal | tail -n 7)
#Skript mis RETURNIB kalendri koos kuupäeva ja kellajaga
echo "Time is $DATE $TIME" 
echo "$CALENDAR"
