#!/bin/bash
#Skripti nimi: kujund.sh
#Autor: Lukas Miguel Noorlaid
#Kirjeldus: Skript küsib kasutajalt ridade arvu ja trükib kujundi, mis koosneb tähest "X", alates suurest kuni väiksemaks.

# Küsi kasutajalt ridade arvu
read -p "Palun sisestage kujundi ridade arv: " ridade_arv

# Kontrolli, et ridade arv on positiivne
if [[ $ridade_arv -gt 0 ]]; then
    for ((i = ridade_arv; i >= 1; i--)); do
        for ((j = 1; j <= i; j++)); do
            echo -n "*"
        done
        echo
    done
else
    echo "Palun sisestage positiivne ridade arv."
fi
