#!/bin/bash
#Skripti nimi: menu.sh
#Autor: Lukas Miguel Noorlaid
#Kirjeldus: Skript kuvab menüü ja vastavalt kasutaja valikule väljastab söögi kirjelduse.

# Menüü kuvamine
echo "Vali toidutüüp:"
echo "1) liha ja kartulid"
echo "2) kala ja krõpsud"
echo "3) supp ja salat"

# Kasutaja valiku küsimine
read -p "Tee oma valik (1 või 2 või 3): " valik

# Vastavalt valikule väljastame kirjelduse
case $valik in
    1)
        echo "Väga maitsev, aga jälgi oma tervist!"
        echo "Head isu!"
        ;;
    2)
        echo "Brititoit on maitsev!"
        echo "Head isu!"
        ;;
    3)
        echo "Nii tervislik ja igav..."
        echo "Head isu!"
        ;;
    *)
        echo "Vale valik! Palun vali 1, 2 või 3."
        ;;
esac
