#!/bin/bash

# Sisend andmed
echo -n "Sisesta reisijate arv: "
read reisijad

echo -n "Sisesta kohtade arv bussis: "
read kohad

# Arvutused
# Arvutame, mitu bussi on vaja
bussid=$((reisijad / kohad))

# Kontrollime, kas on üleliigseid reisijaid
ulejaanud=$((reisijad % kohad))
# Kui on üleliigseid reisijaid, lisame bussi
if [ $ulejaanud -gt 0 ]; then
    bussid=$((bussid + 1))
fi
# Tulemuse väljastus
echo "Kokku on vaja $bussid bussi"
